### ISSUE TITLE
Module Broken

### ISSUE THREAD

**Issue by nasheikh** [AustinCloudGuru/terraform-aws-efs#12]
Error: ConflictsWith
│ 
│   with module.efs.aws_security_group_rule.this_ingress["default"],
│   on .terraform/modules/efs/modules/efs/main.tf line 30, in resource "aws_security_group_rule" "this_ingress":
│   30:   self              = lookup(each.value, "self", null)
│ 
│ "self": conflicts with cidr_blocks
╵
╷
│ Error: ConflictsWith
│ 
│   with module.efs.aws_security_group_rule.this_ingress["default"],
│   on .terraform/modules/efs/modules/efs/main.tf line 31, in resource "aws_security_group_rule" "this_ingress":
│   31:   cidr_blocks       = lookup(each.value, "cidr_blocks", null)
│ 
│ "cidr_blocks": conflicts with self

**Comment by austincloudguru** [comment]
This is a bug in the AWS module.  (https://github.com/hashicorp/terraform-provider-aws/issues/19179).  I've created a new version (v0.8.1) that pins the AWS module to <= 3.37.0(the last know working).  When they fix it, I'll launch a new version and remove the bin.
