### ISSUE TITLE
aws_ecurity_group_rule conflicts

### ISSUE THREAD

**Issue by stevie-** [AustinCloudGuru/terraform-aws-efs#13]
We've noticed an issue with your current setup (version v0.8.0).

```bash
Error: ConflictsWith

  on main.tf line 30, in resource "aws_security_group_rule" "this_ingress":
  30:   self              = lookup(each.value, "self", null)

"self": conflicts with cidr_blocks


Error: ConflictsWith

  on main.tf line 31, in resource "aws_security_group_rule" "this_ingress":
  31:   cidr_blocks       = lookup(each.value, "cidr_blocks", null)

"cidr_blocks": conflicts with self


Error: ConflictsWith

  on main.tf line 41, in resource "aws_security_group_rule" "this_egress":
  41:   self              = lookup(each.value, "self", null)

"self": conflicts with cidr_blocks


Error: ConflictsWith

  on main.tf line 42, in resource "aws_security_group_rule" "this_egress":
  42:   cidr_blocks       = lookup(each.value, "cidr_blocks", null)

"cidr_blocks": conflicts with self
```

In the current [documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group_rule#self)  you can find this:

```
Whether the security group itself will be added as a source to this ingress rule. Cannot be specified with cidr_blocks, ipv6_cidr_blocks, or source_security_group_id.
```

This means you need to have a seperate `aws_security_group_rule` if `self` is `true` and `false`.
Another workaround we use is, to set the parameters we don't want to  `null`

For example in your default parameters you would change them to 

```
variable "security_group_ingress" {
  description = "Can be specified multiple times for each ingress rule. "
  type = map(object({
    description = string
    from_port   = number
    protocol    = string
    to_port     = number
    self        = bool
    cidr_blocks = list(string)
  }))
  default = {
    default = {
      description = "NFS Inbound"
      from_port   = 2049
      protocol    = "tcp"
      to_port     = 2049
      self        = true
      cidr_blocks = null # change to null
    }
  }
}

variable "security_group_egress" {
  description = "Can be specified multiple times for each egress rule. "
  type = map(object({
    description = string
    from_port   = number
    protocol    = string
    to_port     = number
    self        = bool
    cidr_blocks = list(string)
  }))
  default = {
    default = {
      description = "Allow All Outbound"
      from_port   = 0
      protocol    = "-1"
      to_port     = 0
      self        = null # change to null
      cidr_blocks = ["0.0.0.0/0"]
    }
  }
}

```

**Comment by austincloudguru** [comment]
This is a bug in the AWS module. (hashicorp/terraform-provider-aws#19179). I created a new version (v0.8.1) per issue #12 that pinned the AWS module to <= 3.37.0 (the last know working). Since it is not clear if or when they will fix it, and I don't want to wait forever pinned to a specific aws module version, I've updated the code to account for it.  With the change, you can still use true and false for self, but if self is set to false, the code will use null.

**Comment by stevie-** [comment]
The issue for us is, that we want to use provider default_tags feature which starts from `aws >=3.38.0`.

But I can also see your point and we can use v0.8.0 with the workaround mentioned above (`use null as value`)

**Comment by austincloudguru** [comment]
> The issue for us is, that we want to use provider default_tags feature which starts from `aws >=3.38.0`.
> 
> But I can also see your point and we can use v0.8.0 with the workaround mentioned above (`use null as value`)

Sorry if I wasn't clear in my last message.  I've updated it to v0.8.2 which will allow true/false for self but if false will set it to null. This should resolve the issue completely.
