### ISSUE TITLE
[feat] Please add support for lifecycle policy

### ISSUE THREAD

**Issue by aquam8** [AustinCloudGuru/terraform-aws-efs#9]
Hello,

AWS and the Terraform provider have added support for transition to Infrequent storage with `lifecycle_policy` documented [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/efs_file_system).

```
lifecycle_policy {
    transition_to_ia = "AFTER_30_DAYS"
}
```

It would be great if this module could support it too.

Thank you!

**Comment by austincloudguru** [comment]
I've added it.

**Comment by aquam8** [comment]
Brilliant, thank you! And what a fast turnaround 👍
